package com.example.appdaugia.service.response

data class LoginData(
    val token: String?,
    val id: Long?,
    val id_encode: Long?,
    val code: String?,
    val username: String?,
    val name: String?,
    val first_name: String?,
    val full_name: String?,
    val email: String?,
    val status: Int?,
    val avatar: String?,
    val gender: Int?,
    val phone: String?,
    val active: Int?,
    val company: String?,
    val house_number: String?,
    val address: String?,
    val postal_code: String?,
    val location: String?,
    val country: String?,
    val shipping_to: Int?,
    val shipping_fullname: String?,
    val shipping_house_number: String?,
    val shipping_address: String?,
    val shipping_postal_code: String?,
    val shipping_location: String?,
    val shipping_country: String?,
    val tiktok_username: String?,
    val vat_id: String?,
    val prim_number: String?,
    val laverka_number: String?,
    val brosis_number: String?,
    val notifications_auctions: Int?,
    val notifications_newsletter: Int?
)